### Générer le PDF pour le livre avec l'ID 3
GET http://localhost:8000/api/books/3/pdf HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Mzg2ODA4NDUsImV4cCI6MTczODY4NDQ0NSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20ifQ.I2TSqsq1ikJmVewiHWRZubqxybJml3mnU8BHgMzr8DMuXUysBdZfEmoWX2UeMTQQF39k3I9aw9Y_J6yYT4sMd1MwYr6PhP52U3ctGGlM0XF7lbseHuw3L3EMnt_pcVjNYU5YNl_um3dORh6Ih2aKjvfpEi3hCPeHZM_CO16_Wz4pVV66jGXHE4aioYgvGtmDYPHqYypgGOgOaVOHG3dhzLNvimpwQLw_U8frHJBw6IkEg3wgFqMRofiTDmW1BdqsHTPUlUFicuCAydJmh5U8jRBv2xR5fR1qmU6cyfEKnOfavRyXyJcihkdWLQmV_jTtTy0N0Oos7ErOCoqLeOZohA
