### Générer le PDF pour le livre avec l'ID 8
GET http://localhost:8000/api/books/8/pdf HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Mzg5NjI4NTQsImV4cCI6MTczODk2NjQ1NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20ifQ.n3Ti3gbKkPWjGgf5hbuhGjfXcb9h5aBsTfam2MQR8cePIBS3oOtsxHYB2kOSJtKD3ABDdanI75BOoLluBMtb4afzpidfLuvx5AEwm2bpcIXutuRJuI4QHES8-XwiojqBR-mg5TOhEhpmMhb3Wa3sAnwQ0ENB0D4A9gFUptVrqM-NUBpMArrwoJutQBHHePfjYNQjt5eN7YJkP4TRp5-GCk_1pTS8zX5vXimFHL5kMxaNHnxv-aV53lcidRRe5a8Pcv-bSO9zSPl_hyVnpAoTCGDhJQMU7jlRHUsDFnuYWu91S2I-wtVRvW2hb24OZ_hRSOlARj5G_MCfjcOPOKzFxg