POST http://localhost:8000/api/orders/2/checkout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzgzMjAzMTMsImV4cCI6MTczODMyMzkxMywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20ifQ.jk20o7PBRogjWcXNe7YdzqDRUZYDbjM9NDMGTkLx_tWE2_sTn9zC9RdPMbpuFsZqTIbGu__vyVbVwfThanToEQ-guQ5rmuXZPwbbv4TZl_UuyEhhVfdRZX5LEOk-kb4Ll8GIXndIqFRSXeW-sf-uFVCUDwh2PDNTQXafcN31eaFzk9BaiMdY4hqoHqNhLphuidF3p2-58XBJ-F0x4W9QcerEbu9k1QGvB_tbZ0hFHqU7IKqg9aqw6Ik7PqYwDhmF6lF2OIaze3jU1eVEmAYvDMIjzNuRK5i3IKo29ltoiSeXBewIAwyQTeRo0pR7XR2S3O1pGcRo7k5eq8KBWU9Wpw