POST http://localhost:8000/api/books
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3Mzg0NTU0ODAsImV4cCI6MTczODQ1OTA4MCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20ifQ.fAw8Q2GgnqSaUMpcfuyzwPrPzNMDlzXCaP87aOwgazZ6P625o2jFn-ZA2lORGeEtAfBxKoaoIevjk9e6eTfk5qrBvkunc-CiW7YzMKTMS_0aU5kTDI-nO7klnoK13JTA8ysivfWN7b9sUVmJPfNlylQTCnNsMwLiSop3M6xjgVSbZjqf6CvZE6Z6W64q7x9_Hsvz2b-Fk2pdyTKwNuHtdUjivw_c7bDibzKLYlX5e9tKdFpU5WKDgp7DDu8ZdZ1P8Hn-uOq0BKLFbNMjMuMKQrZmbStI5RD9dzkS2X_oVBKWVXROWL0ZRz02mTu-xqWkiqlGTlKi3KwfTCmJ9Wht1Q

{
    "title": "Livre test",
    "child_name": "Silvio",
    "child_age": 8,
    "theme": "adventure",
    "content": "Il était une fois..."
}