GET http://localhost:8000/api/books/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MzgyNDc1NzYsImV4cCI6MTczODI1MTE3Niwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20ifQ.XqPuF107AihE9TEQUB_3YAX0o-SBTZg5sdEWf-8-Fn9rhVES4psAEXiJR6Z5PRIH7DFAtFxQBEgW7CWYeYSKUTmRWVG3oo-E78KvpMHBTps3Q_RCHH2SGRy9iLgI7ghXH_oDw2qjRiOzQqQ7qsKji3vk_sNsqLB1B3kdAabP6y248rTlG7318L34Ys-O_6FDfoalx2j9_LNjUHj8_-IFOiROJW2qhk6RvHVnH0nmdPfmEnW5ZccWHPwfb6mTBvxb9huWRvfjbQVqrRTbE3pmVUxEQBrz6JW4xr7JeBtgOC2PvuOZThtRjNYKgYF9nI-ZDOIQwy9kn-F1G7dM-YImRg